SELECT 
u.SOCIAL_PLATFORM_PREFERENCE,
AVG(f.STRESS_LEVEL) AS AVG_STRESS
FROM {{ source('raw_data', 'DIM_PLATFORM') }} u
JOIN {{ source('raw_data', 'DIM_WELLBEING') }} f
    ON u.PLATFORM_ID = f.WELLBEING_ID
GROUP BY u.SOCIAL_PLATFORM_PREFERENCE
