SELECT 
SCREEN_TIME_BEFORE_SLEEP,
SLEEP_HOURS,
JOB_SATISFACTION_SCORE
FROM {{ source('raw_data', 'DIM_SOCIAL_BEHAVIOUR') }} u
JOIN {{ source('raw_data', 'DIM_WELLBEING') }} f
    ON u.DIGITAL_ID = f.WELLBEING_ID
WHERE JOB_SATISFACTION_SCORE > 8 
