SELECT 
FACT_ID AS MAIN_FACT_ID,
DAILY_SOCIAL_MEDIA_TIME,
PERCEIVED_PRODUCTIVITY_SCORE,
ACTUAL_PRODUCTIVITY_SCORE,
(PERCEIVED_PRODUCTIVITY_SCORE-ACTUAL_PRODUCTIVITY_SCORE) AS NET_PRODUCTIVITY 
FROM {{ source('raw_data','FACT_PRODUCTIVITY') }} 